INSERT INTO guest_groups (id, household_name, access_code, plus_one_limit, notes)
VALUES
  ('grp_' || lower(hex(randomblob(16))), 'Rachel & Reuben', 'PNYPJBXN94KRDB4TKL', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Abraham & Emmy', '66Z9K8SJ322AZ4ATT5', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Anjali & Jensen', '57U9ZMDJWPWXXTPR9N', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Shreenie, Ashwathy & Ashwin', 'JCQGEAHMEL5CUKQPGT', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Dr Arun & Anu', 'TCAUWYUBZJ6EYL2GRZ', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Dr Umesh & Beena', 'HUWR8T6ULYVS62HRY9', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Dr Hemjith & Bindhu', 'YBMY66EX4LWWK7F57V', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Jayan & Meena', 'V4J9G5HGC5T3QBWVFZ', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Vijayanchayan & Monieammama', '2XSUMSXEURX7GTUUMR', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Lalithamamma', 'SXJ2CYXZTUQHNUSH7J', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Robin & Reni', 'UVTPSR7HL748EPG9EF', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Vinitha & Vipin', 'LKP4N9DG9DJMS6PYRD', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Susheelamamma', 'UAGWFLB2HJ2GP4CYJL', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Amandhammama & Daniel Chayan', 'NE4L3RQ9RU3XCD9UHM', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Remanimamma', '664SRUCUGH7BWCN7K6', 0, ''),
  ('grp_' || lower(hex(randomblob(16))), 'Kochumol Ammama & Kunjchayan', '96YPYU28TENF6D2V56', 0, '');

INSERT INTO guests (id, group_id, name, is_primary, is_partner, sort_order)
VALUES
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'PNYPJBXN94KRDB4TKL'), 'Rachel', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'PNYPJBXN94KRDB4TKL'), 'Reuben', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '66Z9K8SJ322AZ4ATT5'), 'Abraham', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '66Z9K8SJ322AZ4ATT5'), 'Emmy', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '57U9ZMDJWPWXXTPR9N'), 'Anjali', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '57U9ZMDJWPWXXTPR9N'), 'Jensen', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'JCQGEAHMEL5CUKQPGT'), 'Shreenie', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'JCQGEAHMEL5CUKQPGT'), 'Ashwathy', 0, 0, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'JCQGEAHMEL5CUKQPGT'), 'Ashwin', 0, 0, 2),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'TCAUWYUBZJ6EYL2GRZ'), 'Dr Arun', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'TCAUWYUBZJ6EYL2GRZ'), 'Anu', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'HUWR8T6ULYVS62HRY9'), 'Dr Umesh', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'HUWR8T6ULYVS62HRY9'), 'Beena', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'YBMY66EX4LWWK7F57V'), 'Dr Hemjith', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'YBMY66EX4LWWK7F57V'), 'Bindhu', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'V4J9G5HGC5T3QBWVFZ'), 'Jayan', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'V4J9G5HGC5T3QBWVFZ'), 'Meena', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '2XSUMSXEURX7GTUUMR'), 'Vijayanchayan', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '2XSUMSXEURX7GTUUMR'), 'Monieammama', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'SXJ2CYXZTUQHNUSH7J'), 'Lalithamamma', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'UVTPSR7HL748EPG9EF'), 'Robin', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'UVTPSR7HL748EPG9EF'), 'Reni', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'LKP4N9DG9DJMS6PYRD'), 'Vinitha', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'LKP4N9DG9DJMS6PYRD'), 'Vipin', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'UAGWFLB2HJ2GP4CYJL'), 'Susheelamamma', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'NE4L3RQ9RU3XCD9UHM'), 'Amandhammama', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = 'NE4L3RQ9RU3XCD9UHM'), 'Daniel Chayan', 0, 1, 1),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '664SRUCUGH7BWCN7K6'), 'Remanimamma', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '96YPYU28TENF6D2V56'), 'Kochumol Ammama', 1, 0, 0),
  ('gst_' || lower(hex(randomblob(16))), (SELECT id FROM guest_groups WHERE access_code = '96YPYU28TENF6D2V56'), 'Kunjchayan', 0, 1, 1);
