ALTER TABLE guests ADD COLUMN sangeet_invited INTEGER NOT NULL DEFAULT 1;
ALTER TABLE guests ADD COLUMN ceremony_invited INTEGER NOT NULL DEFAULT 1;
ALTER TABLE guests ADD COLUMN reception_invited INTEGER NOT NULL DEFAULT 1;
